export default function Head() {
  return (
    <>
      <title>N1se7en</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/unnamed.jpg" />
      
    </>
  )
}
